version: '3'
services:
  nast-server:
    image: nats:latest
    ports:
      - "8222:8222"

  mongo:
    image: mongo:latest
    container_name: mongo_db_auth
    ports:
      - "27017:27017"
  client-gateway:
    build: ./client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:3000
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
      - NAST_SERVERS=nats://nast-server:4222

  products-ms:
    build: ./products-ms
    volumes:
      - ./products-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3001
      - NAST_SERVERS=nats://nast-server:4222
      - DATABASE_URL=file:./dev.db
  payments-ms:
    build: ./payments-ms
    ports:
      - 3003:3003
    volumes:
      - ./payments-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3003
      - NAST_SERVERS=nats://nast-server:4222
      - STRIPE_API_KEY=${STRIPE_API_KEY}
      - STRIPE_SUCCESS_URL=http://localhost:3003/payments/success
      - STRIPE_CANCEL_URL=http://localhost:3003/payments/cancel
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
  
  auth-clients-ms:
    depends_on:
      - mongo
    build: ./auth-clients-ms
    volumes:
      - ./auth-clients-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3004
      - NAST_SERVERS=nats://nast-server:4222
      - DATABASE_URL=mongodb://mongo_db_auth:27017/AuthDb
      - JWT_SECRET=estoDeberiaSerUnStringSeguro
  orders-ms:
    depends_on:
      - orders-db
    build: ./orders-ms
    volumes:
      - ./orders-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3002
      - NAST_SERVERS=nats://nast-server:4222
      - DATABASE_URL=postgresql://postgres:123456@orders-db:5432/ordersdb?schema=public

  orders-db:
    container_name: orders-db
    image: postgres:16.2
    restart: always
    volumes:
      - ./orders-ms/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=ordersdb

    